### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by chipped** [anekol/homebridge-ness-d16x#2]
Hi,

Sorry if this isn't the right place to ask these questions, I wasn't sure where else.

I'm a Security Installer and I've been looking for a Alarm System which will integrate well into Apple Homekit via Homebridge (or Hoobs in my case).

I was just wondering what exact functionality will this give me exactly? I haven't installed Ness Alarms before so I'm not familiar with their terminology however this is basically what I'm looking to achieve with Homekit via Homebridge in order of priority:

1. Arm/Disarm the Alarm manually
2. Notifications for Alarm Events
3. Automatically Arm the System when nobody on premises (like Geofencing, is this done by Homekit somehow? Never tried an Alarm in Homekit before)
4. Automatically Disarm the Alarm when somebody arrives
5. Notifications for System Troubles

I realise this is not all done by the plugin.

I'm just curious how much of the Ness Alarm System is exposed to Homekit via Homebridge and if I would be able to make it work how I've mentioned above.

If only some can be accomplished could you please let me know which ones.

Thanks very much.

**Comment by gregjohnsonsaltaire** [comment]
Hi,

The plugin interfaces with a Ness D8x/D16X panel to implement the functionality defined by the Apple HomeKit Security System Accessory.

This means it provides:

	• Arm/Disarm the Alarm manually

	
	

	• Notifications for Alarm Events - via Home Automations

	
	• Automatically Arm the System when nobody on premises (like Geofencing, is this done by Homekit somehow? Never tried an Alarm in Homekit before)

		Using Home Automations as per above

	• Automatically Disarm the Alarm when somebody arrives

		Using Home Automations as per above

	• Notifications for System Troubles

		No interface is provided by Apple Home to act on this (that I’m aware of, although I’ve not investigated or considered this thoroughly)

Let me know if you’d like any more info or explanation ...

**Comment by gregjohnsonsaltaire** [comment]
… and the Trigger automation:
