### ISSUE TITLE
Issues with Outputs 

### ISSUE THREAD

**Issue by Grant-murphy1** [anekol/homebridge-ness-d16x#5]
Hi, I am having an issues where my outputs are not responding. Could someone please run me through the steps to ensure I have done this correctly? Sorry I am very new to this. 
Thank you

**Comment by gregjohnsonsaltaire** [comment]
Hi, have just updated README re support ...
Can you post your request to https://forums.whirlpool.net.au/thread/3jm6pwkq please ...
What are your expectations as to how your outputs "should" be "responding"?
How is what you're seeing different from your expectations?
Tx ...
