### ISSUE TITLE
Arming / Disarming status not updating correctly

### ISSUE THREAD

**Issue by Grant-murphy1** [anekol/homebridge-ness-d16x#7]
Hey Greg

I have this plug-in installed at my house and my office, both working well but both have a similar issue where as if we arm the alarm to away via the keypad and not through HomeKit, than it sits as “disarming” in HomeKit

It says like this until I disarm and rearm through HomeKit

I’ve tried shortening the exit delay to 2sec and the problem still occurs

Other than that I can’t fault this plug-in and it works so smoothly compared to the standard ness icomms

Thanks Greg

**Comment by gregjohnsonsaltaire** [comment]
Fixed with release v1.0.0
